name: Upgrade packages
'on':
  push:
    branches:
      - ci-cd
permissions:
  contents: write
jobs:
  main:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Install JQ
        run: sudo apt-get install jq

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ci-cd

      - name: Check for updates
        run: |
          chmod +x .github/workflows/upgrader/upgrader.sh
          ./.github/workflows/upgrader/upgrader.sh
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Commit changes
        run: |
          git config --global user.name "Achyut Neupane"
          git config --global user.email "achyutkneupane@gmail.com"
          
          git diff --quiet && git diff --staged --quiet || git commit -am "build(deps): Update dependency versions" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependency versions
          title: Update dependency versions
          body: |
            This is an automated PR to update dependency versions.
            Please review and merge this PR if it looks good.
          branch: ci-cd
          branch-suffix: timestamp
          delete-branch: true
          labels: dependencies
          reviewers: achyutkneupane
          assignees: achyutkneupane
