name: Upgrade packages
'on':
  push:
    branches:
      - ci-cd
permissions:
  contents: write
jobs:
  main:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Install JQ
        run: sudo apt-get install jq

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ci-cd

      - name: Check for updates
        run: |
          chmod +x .github/workflows/upgrader/upgrader.sh
          ./.github/workflows/upgrader/upgrader.sh
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Commit changes
        run: |
          git config --global user.name "Achyut Neupane"
          git config --global user.email "achyutkneupane@gmail.com"
          
          git diff --quiet && git diff --staged --quiet || git commit -am "build(deps): Update dependency versions" || echo "No changes to commit"

      - name: Push changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/ci-cd'
        run: |
          git push origin ci-cd
