name: Bump version
on:
  push:
    branches:
      - master
      - dev
jobs:
  build:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}